name: Automated Internship Bot

on:
  schedule:
    # Run every 5 hours (at 00:00, 05:00, 10:00, 15:00, 20:00 UTC)
    - cron: "0 */5 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-internship-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Smart Internship Bot
        env:
          # Add these secrets in your GitHub repo settings
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        run: |
          # First collect new internships
          python collect.py

          # Then send batch if any new ones found
          python send_batch_email_only.py
