name: Automated Internship Bot

on:
  schedule:
    # Run every 5 hours (at 00:00, 05:00, 10:00, 15:00, 20:00 UTC)
    - cron: "0 */5 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-internship-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing to repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Smart Internship Bot
        env:
          # Add these secrets in your GitHub repo settings
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}
        run: |
          # First process any unsubscribe requests (email-based)
          python email_unsubscribe_processor.py || echo "Unsubscribe processing failed, continuing..."

          # Then collect new internships
          python collect.py

          # Finally send batch if any new ones found (will automatically filter unsubscribed emails)
          python send_batch_email_only.py

      - name: Save unsubscribe updates (optional)
        run: |
          # Just log the unsubscribe status, don't commit back
          if [ -f "unsubscribed_emails.json" ]; then
            echo "📧 Unsubscribe list updated:"
            cat unsubscribed_emails.json
          else
            echo "📭 No unsubscribes processed"
          fi
